spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mystocks
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
mybatis:
  mapper-locations: classpath:mappers/*.xml
logging:
  level:
    org.springframework.web: "debug"
    org.hibernate: "error"